services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: bankappdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost","-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports: 
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bankappnw
  
  bankapp:
    build: .
    container_name: bankapp
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: bankappdb
      MYSQL_USER: root 
      MYSQL_PASSWORD: Test@123
      ollama_URL: http://ollama:11434
    depends_on:
      mysql:
        condition: service_healthy
      ollama:
        condition: service_started
    networks:
      - bankappnw
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports: 
      - "11434:11434"
    networks: 
      - bankappnw
    volumes:
      - ollama-data:/root/.ollama
networks:
  bankappnw:
    driver: bridge

volumes:
  mysql-data:
  ollama-data:

