name: Dependency Scan

on:
  workflow_call:

jobs:
  owasp-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Verify Java
      run: |
        java -version
        echo "JAVA_HOME=$JAVA_HOME"

    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "ai-bankapp"
        path: "."
        format: "HTML"
        args: "--failOnCVSS 7"

    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: reports
