name: dependency scan
on: 
    workflow_call:
jobs:
    owasp-scan:
      runs-on: ubuntu-latest

      steps:
       - name: Checkout Code
         uses: actions/checkout@v4

       - name: Setup Java
         uses: actions/setup-java@v4
         with:
           distribution: temurin
           java-version: '21'

       - name: Download Dependency Check
         run: |
          wget https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.8/dependency-check-12.1.8-release.zip
          unzip dependency-check-12.1.8-release.zip

       - name: Run Dependency Check
         run: |
          ./dependency-check/bin/dependency-check.sh \
          --project "AI-Bank-App" \
          --scan . \
          --format HTML \
          --out reports \
          --failOnCVSS 7

       - name: Upload Report
         uses: actions/upload-artifact@v4
         with:
          name: dependency-check-report
          path: reports